model_parameters:
  model_name: "/llm/intelmc8/models/DeepSeek-R1-Distill-Qwen-32B"
  revision: "main"
  load_in_low_bit: "fp8"
  distributed_executor_backend: "ray"
  dtype: "float16"
  tensor_parallel_size: 4
  data_parallel_size: 1
  pipeline_parallel_size: 1
  gpu_memory_utilization: 0.95
  max_model_length: 35585
  swap_space: 16
  seed: 42
  trust_remote_code: True
  use_chat_template: True
  add_special_tokens: True
  multichoice_continuations_start_space: False
  pairwise_tokenization: False
  subfolder: null
  max_num_seqs: 2
  max_num_batched_tokens: 35585
  generation_parameters:
    temperature: 0.6
    top_p: 0.95
    seed: 42
    max_new_tokens: 32768
metrics_options:
  yo: null